dataset:
  rafdb:
    resize: 224
model:
  aict:
    alpha: 0.3
    att_dropout: 0.4
    conv_number: 1
    dataset: bitcoinAlpha
    dataset_fold: 0
    dropout: 0.7
    feature_dim: null
    hid_dim: 128
    in_dim: 64
    k_e: 3
    k_n: 3
    low_bound: 0.8
    min_num_edges: 100
    namuda: 30
    namuda2: 10
    nheads: 4
    node_dropout: 0.6
    num_edges: 90
    only_x: false
    others_loss: false
    self_attention_heads: 4
    transfer: 1
    up_bound: 0.95
  resnet:
    arch: resnet18
    img_channels: 3
    num_classes: 7
    pretrained: false
  slgnn_tdhnn:
    alpha: 0.2
    att_dropout: 0.8
    bias_hgnn: true
    common_neighbors: false
    dataset: bitcoinAlpha
    dataset_fold: 0
    feature_dim: null
    hid_dim: 128
    in_dim: 64
    k_e: 315
    k_n: 64
    low_bound: 0.5
    min_num_edges: 350
    nheads: 4
    node_dropout: 0.2
    num_edges: 500
    up_bound: 0.6
optim:
  adagrad:
    lr: 0.01
    max_norm: null
    no_weight_decay_on_bn: false
    weight_decay: 0.001
  adagrad_ca:
    T_max: null
    lr: 0.01
    max_norm: null
    no_weight_decay_on_bn: false
    weight_decay: 0.001
  adam:
    amsgrad: false
    betas: &id002 !!python/tuple
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.01
    max_norm: null
    no_weight_decay_on_bn: false
    weight_decay: 0.001
  adam_ca:
    T_max: null
    amsgrad: false
    betas: &id001 !!python/tuple
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.0001
    max_norm: null
    no_weight_decay_on_bn: false
    weight_decay: 0
  adam_multistep:
    amsgrad: false
    betas: *id001
    eps: 1.0e-08
    gama: 0.1
    lr: 0.01
    max_norm: null
    milestones:
    - 5
    - 10
    no_weight_decay_on_bn: false
    weight_decay: 0
  adam_step:
    gamma: 0.5
    lr: 0.005
    max_norm: null
    no_weight_decay_on_bn: false
    step_size: 30
  adamw:
    amsgrad: false
    betas: *id002
    eps: 1.0e-08
    lr: 0.01
    max_norm: null
    no_weight_decay_on_bn: false
    weight_decay: 0.0001
  sgd:
    lr: 0.01
    max_norm: null
    momentum: 0.9
    no_weight_decay_on_bn: false
    weight_decay: 0.0001
  sgd_ca:
    T_max: null
    lr: 0.01
    max_norm: null
    momentum: 0
    no_weight_decay_on_bn: false
    weight_decay: 0
  sgd_multistep:
    gama: 0.1
    lr: 0.01
    max_norm: 10.0
    milestones:
    - 60
    - 100
    momentum: 0
    no_weight_decay_on_bn: true
    weight_decay: 0
  sgd_step:
    gamma: 0.5
    lr: 0.005
    max_norm: null
    momentum: 0.9
    no_weight_decay_on_bn: false
    step_size: 30
    weight_decay: 0.0005
